// <auto-generated />
using System;
using DevBudy.PERSISTANCE.ContextClasses;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevBudy.PERSISTANCE.Migrations
{
    [DbContext(typeof(DevBudyContext))]
    partial class DevBudyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DevBudy.DOMAIN.Entities.Concretes.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActiveStatus")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DataStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActiveStatus = 1,
                            ConcurrencyStamp = "8f0baa58-ce22-4de9-ae16-748fe832e596",
                            CreatedDate = new DateTime(2025, 7, 17, 17, 1, 35, 684, DateTimeKind.Local).AddTicks(8130),
                            DataStatus = 1,
                            Name = "Developer",
                            NormalizedName = "DEVELOPER"
                        },
                        new
                        {
                            Id = 2,
                            ActiveStatus = 1,
                            ConcurrencyStamp = "8a24b18a-ea7b-482d-9194-ba31553f213e",
                            CreatedDate = new DateTime(2025, 7, 17, 17, 1, 35, 684, DateTimeKind.Local).AddTicks(8218),
                            DataStatus = 1,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 3,
                            ActiveStatus = 1,
                            ConcurrencyStamp = "8d548d41-ac36-4270-b956-d45f008671c6",
                            CreatedDate = new DateTime(2025, 7, 17, 17, 1, 35, 684, DateTimeKind.Local).AddTicks(8222),
                            DataStatus = 1,
                            Name = "Member",
                            NormalizedName = "MEMBER"
                        });
                });

            modelBuilder.Entity("DevBudy.DOMAIN.Entities.Concretes.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("ActivationCode")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActiveStatus")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DataStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPersonalDataConsentGiven")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastActivityTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastLogout")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ActiveStatus = 1,
                            ConcurrencyStamp = "7367ed6f-5677-447c-8ebf-7b02a0bd2e89",
                            CreatedDate = new DateTime(2025, 7, 17, 17, 1, 35, 684, DateTimeKind.Local).AddTicks(8435),
                            DataStatus = 1,
                            Email = "ekrmdsgnr@gmail.com",
                            EmailConfirmed = true,
                            IsPersonalDataConsentGiven = false,
                            LastActivityTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastLogin = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastLogout = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NormalizedEmail = "EKRMDSGNR@GMAIL.COM",
                            NormalizedUserName = "EKREM.GUNGOR",
                            PasswordHash = "AQAAAAIAAYagAAAAEDNNDKlMfAGlW2nK71u/AneFx2B4vmoiI8aS4i58pbnwELYt4JatHKDkd8NVMrahTw==",
                            PhoneNumber = "12345678910",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "18a184c4-e910-4fcc-9bc8-f50018516045",
                            TwoFactorEnabled = false,
                            UserName = "ekrem.Gungor"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ActiveStatus = 1,
                            ConcurrencyStamp = "c73e488e-b15d-4cea-8971-8316a4b28266",
                            CreatedDate = new DateTime(2025, 7, 17, 17, 1, 35, 749, DateTimeKind.Local).AddTicks(1146),
                            DataStatus = 1,
                            Email = "canberk.gunduz@example.com",
                            EmailConfirmed = true,
                            IsPersonalDataConsentGiven = false,
                            LastActivityTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastLogin = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastLogout = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NormalizedEmail = "CANBERK.GUNDUZ@EXAMPLE.COM",
                            NormalizedUserName = "CANBERK.GUNDUZ",
                            PasswordHash = "AQAAAAIAAYagAAAAEA30OrRzNQUATJcE9RuN6l7J6/67Awj2jO38g7D7pYSNvgapHL60Fw1V+kZWuA8WrA==",
                            PhoneNumber = "12345678910",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6ba05ae4-0278-459c-8411-c2d5e65425c2",
                            TwoFactorEnabled = false,
                            UserName = "canberk.Gunduz"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ActiveStatus = 1,
                            ConcurrencyStamp = "a8077fa5-48e2-4c57-bee6-97c078faf09c",
                            CreatedDate = new DateTime(2025, 7, 17, 17, 1, 35, 821, DateTimeKind.Local).AddTicks(2507),
                            DataStatus = 1,
                            Email = "gunguzsenemm@gmail.com",
                            EmailConfirmed = true,
                            IsPersonalDataConsentGiven = false,
                            LastActivityTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastLogin = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastLogout = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NormalizedEmail = "GUNGUZSENEMM@GMAIL.COM",
                            NormalizedUserName = "SENEM.GUNDUZ",
                            PasswordHash = "AQAAAAIAAYagAAAAEI79B9THFOM4QrehAIh5mbK0DbTLpZhsE0Cy3rlF8juautP1kazQ6Te59v6/0WupcA==",
                            PhoneNumber = "12345678910",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "df564e47-b80e-4b44-b43f-debc3a9a601c",
                            TwoFactorEnabled = false,
                            UserName = "senem.Gunduz"
                        });
                });

            modelBuilder.Entity("DevBudy.DOMAIN.Entities.Concretes.AppUserProfile", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<int>("ActiveStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DataStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("AppUserProfiles");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ActiveStatus = 1,
                            CreatedDate = new DateTime(2025, 7, 17, 17, 1, 35, 684, DateTimeKind.Local).AddTicks(8408),
                            DataStatus = 1,
                            FirstName = "Ekrem",
                            LastName = "Güngör"
                        },
                        new
                        {
                            ID = 2,
                            ActiveStatus = 1,
                            CreatedDate = new DateTime(2025, 7, 17, 17, 1, 35, 684, DateTimeKind.Local).AddTicks(8410),
                            DataStatus = 1,
                            FirstName = "Canberk",
                            LastName = "Gündüz"
                        },
                        new
                        {
                            ID = 3,
                            ActiveStatus = 1,
                            CreatedDate = new DateTime(2025, 7, 17, 17, 1, 35, 684, DateTimeKind.Local).AddTicks(8411),
                            DataStatus = 1,
                            FirstName = "Senem",
                            LastName = "Gündüz"
                        });
                });

            modelBuilder.Entity("DevBudy.DOMAIN.Entities.Concretes.AppUserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("ActiveStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DataStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1,
                            ActiveStatus = 1,
                            CreatedDate = new DateTime(2025, 7, 17, 17, 1, 35, 889, DateTimeKind.Local).AddTicks(7309),
                            DataStatus = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2,
                            ActiveStatus = 1,
                            CreatedDate = new DateTime(2025, 7, 17, 17, 1, 35, 889, DateTimeKind.Local).AddTicks(7324),
                            DataStatus = 1
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 3,
                            ActiveStatus = 1,
                            CreatedDate = new DateTime(2025, 7, 17, 17, 1, 35, 889, DateTimeKind.Local).AddTicks(7326),
                            DataStatus = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DevBudy.DOMAIN.Entities.Concretes.AppUserProfile", b =>
                {
                    b.HasOne("DevBudy.DOMAIN.Entities.Concretes.AppUser", "AppUser")
                        .WithOne("Profile")
                        .HasForeignKey("DevBudy.DOMAIN.Entities.Concretes.AppUserProfile", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("DevBudy.DOMAIN.Entities.Concretes.AppUserRole", b =>
                {
                    b.HasOne("DevBudy.DOMAIN.Entities.Concretes.AppRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevBudy.DOMAIN.Entities.Concretes.AppUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("DevBudy.DOMAIN.Entities.Concretes.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("DevBudy.DOMAIN.Entities.Concretes.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("DevBudy.DOMAIN.Entities.Concretes.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("DevBudy.DOMAIN.Entities.Concretes.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevBudy.DOMAIN.Entities.Concretes.AppRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("DevBudy.DOMAIN.Entities.Concretes.AppUser", b =>
                {
                    b.Navigation("Profile")
                        .IsRequired();

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
